// Build script: precompute the full bar list (Google Places + website "screens /
// World Cup" enrichment) for the visible cities + curated New York & Boston, and
// write the committed snapshot src/.. → server/venuesSnapshot.js. The app then
// serves this instantly with NO runtime Places/website calls.
//
//   node scripts/build-venues.mjs        (or: npm run build:venues)
//
// Requires GOOGLE_MAPS_API_KEY in .env. Re-run to refresh, or when onboarding a
// new city (add its config first). Accepted trade-off: data is frozen between runs.
import 'dotenv/config'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { CITY_LIST, getCity } from '../src/lib/city.js'
import { buildCityVenues } from '../server/buildVenues.js'

const KEY = process.env.GOOGLE_MAPS_API_KEY
if (!KEY) {
  console.error('Missing GOOGLE_MAPS_API_KEY in .env')
  process.exit(1)
}

const here = dirname(fileURLToPath(import.meta.url))
const OUT = resolve(here, '../server/venuesSnapshot.js')

// Visible cities + curated-but-hidden New York & Boston (ready to enable later).
const extra = ['new-york', 'boston']
const cities = [...CITY_LIST]
for (const id of extra) {
  if (!cities.some((c) => c.id === id)) cities.push(getCity(id))
}

const snapshot = {}
let total = 0
for (const city of cities) {
  process.stdout.write(`Building ${city.id}… `)
  try {
    const { venues, source, reason } = await buildCityVenues(city, KEY)
    const withCheck = venues.filter((v) => v.check).length
    snapshot[city.id] = { generatedAt: new Date().toISOString(), venues }
    total += venues.length
    console.log(`${venues.length} venues (${withCheck} with check) · ${source}${reason ? ' · ' + reason : ''}`)
  } catch (e) {
    console.log(`FAILED: ${e.message}`)
    snapshot[city.id] = { generatedAt: new Date().toISOString(), venues: [] }
  }
}

const header =
  '// GENERATED by scripts/build-venues.mjs — do not edit by hand.\n' +
  '// Precomputed Google Places venues + baked website checks per city.\n' +
  `// Cities: ${cities.map((c) => c.id).join(', ')}\n`
writeFileSync(OUT, `${header}export const VENUES_SNAPSHOT = ${JSON.stringify(snapshot)}\n`)
console.log(`\nWrote ${OUT} — ${cities.length} cities, ${total} venues total.`)
